### ISSUE TITLE
How do I build the simple HD wallet UI?

### ISSUE THREAD

**Issue by rakeshgn31** [trezor/hd-wallet#1]
@jpochyla  Hi... I am trying to build this hd wallet and launch the wallet on my local machine. I cloned the repo and got the trezor-crypto library. When I do "make example server", it says "Serving http... on ...". When I go to the localhost/dist/example.html. I am not able to see the wallet UI rather two buttons which are not working again.

**Comment by karelbilek** [comment]
Hello, we didn't update the examples for a while at all.

I have updated the example to the newest version of the library, and you can see it on github pages also

http://trezor.github.io/hd-wallet/example.html

note that it's very rudimentary. What this library does is basically just account discovery; you give it xpub and it returns you list of transactions, utxos, balances, even when the backend is "only" bitcore that don't know anything about xpubs.
