### ISSUE TITLE
can fastxpub used in electron application?

### ISSUE THREAD

**Issue by KevinBaiSg** [trezor/hd-wallet#34]

**Comment by prusnak** [comment]
Node 11 supports webworkers, so it should work there.

**Comment by KevinBaiSg** [comment]
thanks @prusnak 
do you have others way to discovery account information and build tx if I don't use the fastxpub?

**Comment by prusnak** [comment]
No

**Comment by KevinBaiSg** [comment]
@prusnak electron support webworker on the render thread by set nodeIntegrationInWorker is true.
but in my code, it always call discovery.dispose(e); 
![image](https://user-images.githubusercontent.com/2813260/52528212-afe28f80-2d13-11e9-8d49-3c8ea350cd73.png)

**Comment by KevinBaiSg** [comment]
@prusnak I can't receive anything from getAddressHistroy
![image](https://user-images.githubusercontent.com/2813260/52529380-aa913f00-2d2b-11e9-8333-52ddc8d5f5f6.png)

**Comment by karelbilek** [comment]
node doesn't actually support webworkers, but electron is Chrome, so it might work? I don't know

**Comment by karelbilek** [comment]
or maybe it's some issue with our backend not supporting connections except from the web wallet.

**Comment by KevinBaiSg** [comment]
thanks @karel-3d 
the params are empty when calling getAddressHistroy. but the addresses are generated inside by xpub. I have passed it correctly. I don't know what happens? can you help me?

**Comment by KevinBaiSg** [comment]
I am sure the addresses array is empty when calling getAddressHistory. But I can not track where derive the addresses. My project is open source, so can you help me debug this issues?
