### ISSUE TITLE
Need to upgrade 'socket.io-client' to solve some security issues

### ISSUE THREAD

**Issue by webees** [trezor/hd-wallet#37]
![image](https://user-images.githubusercontent.com/5155291/55055981-bb113500-509f-11e9-8858-fbcf03970679.png)

**Comment by szymonlesisz** [comment]
also it needs to be upgraded as a fix for node.js:
https://github.com/socketio/engine.io-client/pull/613

**Comment by szymonlesisz** [comment]
8.2.4 released with socket.io-client@2.2.0
