### ISSUE TITLE
McAfee Antivirus detected JS/Miner.bu

### ISSUE THREAD

**Issue by dmitrystas** [trezor/hd-wallet#53]
Affected file is /hd-wallet/lib/fastxpub/fastxpub.js

Link to scan result is https://www.virustotal.com/gui/file/1488a755a0c651edbaad4341afb7e0d2d610008edb0b604680dacb095949a89d/detection

**Comment by prusnak** [comment]
False positive. Stupid antiviruses mark anything related to bitcoin as malicious.
